name: bazzite-bc250
description: Custom Bazzite image for AMD BC-250 with aic8800 and nct6687 drivers.
base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: rpm-ostree
    install:
      - git
      - make
      - gcc
      - gcc-c++
      - dkms
      - rpm-build
      - kernel-devel
      - kernel-headers
      - lm_sensors

  - type: script
    scripts:
      - install-nct6687d.sh
