name: bazzite-bc250
description: Custom Bazzite image for AMD BC-250 with aic8800 and nct6687 drivers.
base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: rpm-ostree
    install:
      - git
      - make
      - gcc
      - gcc-c++
      - kernel-devel
      - kernel-headers
      - lm_sensors

  - type: script
    snippets:
      - |
        set -euxo pipefail

        cd /tmp

        git clone https://github.com/Fred78290/nct6687d.git
        cd nct6687d

        make

        mkdir -p /usr/lib/modules/$(uname -r)/extra

        cp nct6687.ko /usr/lib/modules/$(uname -r)/extra/

        depmod -a $(uname -r)

        cat >/etc/modules-load.d/nct6687.conf <<EOF
        nct6687
        EOF

        cat >/etc/modprobe.d/nct6687.conf <<EOF
        options nct6687 fan_config=msi_alt1
        EOF
